In [4]:
import numpy as np
  
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[-2147483647,           0,  1339174003],
       [         20,        1281,  1039514339],
       [          0,    83886080, -1332079741],
       [          0,          21,        1001]])

In [2]:
import numpy as np
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Flatten, Conv2D
import tensorflow as tf
a = np.array([[1, 2, 4, -1],
              [3, 2, 5, 1],
              [1, 8, 3, -77]])
print(a)
print("TensorFlow version:", tf.__version__)


[[  1   2   4  -1]
 [  3   2   5   1]
 [  1   8   3 -77]]
TensorFlow version: 2.8.0


In [6]:
while True:
    try:
        x = int(input("Please enter a number: "))
        print(x)
        break
        
    except ( ValueError, RuntimeError, TypeError, NameError) as err:
        print(f"Oops!...{err}")
        # raise


45
