In [1]:
import numpy as np
  
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')
a = np.array([[1, 2, 4, -1],
              [3, 2, 5, 1],
              [1, 8, 3, -77]])
print(a)


[[  1   2   4  -1]
 [  3   2   5   1]
 [  1   8   3 -77]]


In [2]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Flatten, Conv2D
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
tf.keras.layers.dot


TensorFlow version: 2.8.0


<function keras.layers.merge.dot(inputs, axes, normalize=False, **kwargs)>