In [8]:
import numpy as np
  
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')
a = np.array([[1, 2, 4, -1],
              [3, 2, 5, 1],
              [1, 8, 3, -77]])
print(a)


[[  1   2   4  -1]
 [  3   2   5   1]
 [  1   8   3 -77]]


In [10]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Flatten, Conv2D
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
tf.keras.layers.dot


TensorFlow version: 2.8.0


<function keras.layers.merge.dot(inputs, axes, normalize=False, **kwargs)>

     NAME           ADDRESS      CONTACT                COMPANY  \
0  Elijah        London, UK  44555332384              Bloomberg   
1  Elisha            Canada  12300444833          Pure-Gold, Ca   
2    Mary             China  86747282993  Huoung Medical Center   
3    Emma  Germany, Hamburg  46729882939                 Amazon   
4   David               USA  12283489304           Newmont Ltd.   

             OCCUPATION  
0     Software Engineer  
1    Executive Director  
2  Medical Practitioner  
3       Senior Engineer  
4      Engineer Manager  
...........................................
    NAME           ADDRESS      CONTACT       COMPANY        OCCUPATION
3   Emma  Germany, Hamburg  46729882939        Amazon   Senior Engineer
4  David               USA  12283489304  Newmont Ltd.  Engineer Manager
